### ISSUE TITLE
Expand Unicode support for other tags

### ISSUE THREAD

**Issue by Michael14K** [ddyos/UnicodeExifInterface#2]
Hi,

firstly, thanks for your work on this project. 
Any chance you could expand the support of writing in Unicode for other tags, e.g. TAG_CAMERA_OWNER_NAME, TAG_COPYRIGHT, TAG_IMAGE_DESCRIPTION, TAG_MAKER_NOTE, and so on...?

Thanks again!

**Comment by ddyos** [comment]
Hi,
Form the document of Exif file format,
"UserComment"  tag's format is "undefined", and description is "...... This tag allows to use two-byte character code or unicode. First 8 bytes describe the character code .......".
But other tags don't have the same format and description.
So, just the "UserComment" tag can writing in Unicode if we follow the document.

**Comment by Michael14K** [comment]
Thanks for your answer, makes sense! Anyway, thank you for working on this project. It is a great help!

**Comment by ddyos** [comment]
Thank you. I'm glad this project can help you.
